### ISSUE TITLE
stdin.setRawMode is not a function

### ISSUE THREAD

**Issue by hedgerh** [vadimdemedes/ink-select-input#18]
When trying to spin up a simple example of the SelectInput using the demo code sample, I'm getting

```
(node:4893) UnhandledPromiseRejectionWarning: TypeError: stdin.setRawMode is not a function
    at App.isEnabled (/Users/hh68154/Desktop/Keep/sites/cli/node_modules/ink/build/components/App.js:47:17)
    at SelectInput.componentDidMount (/Users/hh68154/Desktop/Keep/sites/cli/node_modules/ink-select-input/build/SelectInput.js:153:5)
```

I'm using `"ink": "^2.0.0",` and `"ink-select-input": "^3.1.0",`.  Any idea what the problem may be?

**Comment by hedgerh** [comment]
Nevermind.  Found the issue.  I was using `nodemon`.   The solution can be found here https://github.com/vadimdemedes/ink-text-input/issues/25 for anyone else looking
